---

env:
  es6: true

ignorePatterns:
  - '*.svelte'

overrides:
  -
    files:
      - '*.js'
    env:
      node: true
    parserOptions:
      ecmaVersion: 2023
      sourceType: module
    extends:
      - '@matthiaskunnen/eslint-config-base'
    rules:
      indent:
        - error
        - tab
      no-tabs: off

  -
    files:
      - 'src/**/*.ts'
    extends:
      - '@matthiaskunnen/eslint-config-typescript'
    parserOptions:
      project:
        - tsconfig.json
    rules:
      '@typescript-eslint/naming-convention':
        - error
        - format:
            - camelCase
          selector: default
        - format:
            - camelCase
            - PascalCase
          selector: import
        - format:
            - PascalCase
          selector: typeLike
        - format:
            - PascalCase
          selector: enumMember
        - format:
            - camelCase
          leadingUnderscore: allow
          selector: method
        - format:
            - camelCase
          leadingUnderscore: allow
          selector: parameter
        - format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
          selector: variable
        - format:
            - camelCase
            - PascalCase
            - UPPER_CASE
          modifiers:
            - const
          selector: variable
        - format:
          selector: classProperty
        - format:
          selector: objectLiteralProperty
        - format:
          selector: typeProperty
      '@typescript-eslint/no-var-requires': off
      indent:
        - error
        - tab
      no-console: off
      no-tabs: off

  -
    files:
      - vite.config.ts
    env:
      node: true
    extends:
      - '@matthiaskunnen/eslint-config-typescript'
    parserOptions:
      project:
        - tsconfig.json
    rules:
      indent:
        - error
        - tab
      no-tabs: off
